apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: argocd.prinzba.ch
  namespace: argocd
spec:
  endpoints:
    - dnsName: argocd.prinzba.ch
      recordTTL: 180
      recordType: A
      targets: [ "" ]