apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: argocd.prinzba.ch
  namespace: argocd
spec:
  endpoints:
    - dnsName: argocd.prinzba.ch
      recordTTL: 1
      recordType: A
      targets:
        - 192.168.1.200