apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-argocd-oauth-client-id
  namespace: argocd
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
  data:
    - remoteRef:
        key: /github/oauth-argo/client-id
      secretKey: client-id
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    deletionPolicy: Delete