apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-argocd-oauth-client-id
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  data:
    - remoteRef:
        key: /argocd/google-oauth/client-id
      secretKey: client-id
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    deletionPolicy: Delete