apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  server.insecure: "false"
  users.anonymous.enabled: "false"
  url: https://argocd.prinzba.ch
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-argocd-oauth-client-id:client-id
          clientSecret: $github-argocd-oauth-client-secret:client-secret
          redirectURI: https://argocd.prinzba.ch/dex/callback
          orgs:
          - name: castillo-k8s
            teams:
            - Admins

