apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  server.insecure: "false"
  users.anonymous.enabled: "false"
  url: https://argocd.prinzba.ch
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-argocd-oauth-client-id:client-id
          clientSecret: $github-argocd-oauth-client-secret:client-secret
