apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  server.insecure: "false"
  users.anonymous.enabled: "false"
  url: https://argocd.prinzba.ch
  oidc.config: |
    name: Keycloak
    issuer: https://auth.prinzba.ch/realms/argocd
    clientID: argocd
    clientSecret: $keycloak-oauth-client-secret:client-secret-base64
    requestedScopes: ["openid", "profile", "email", "groups"]

