apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  server.insecure: "false"
  users.anonymous.enabled: "false"
  url: https://argocd.prinzba.ch
  dex.config: |
    connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: $google-argocd-oauth-client-id:client-id
          clientSecret: $google-argocd-oauth-client-secret:client-secret

