apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kargo
  namespace: kargo
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-lets-encrypt
    kubernetes.io/ingress.class: public
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - kargo.joachimprinzbach.com
      secretName: kargo-api-cert
  rules:
    - host: kargo.joachimprinzbach.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kargo-api
                port:
                  number: 80

---

apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: "kargo.joachimprinzbach.com"
  namespace: kargo
spec:
  endpoints:
    - dnsName: "kargo.joachimprinzbach.com"
      recordTTL: 180
      recordType: CNAME
      targets:
        - "joachimprinzbach.com"