apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: homeassistant-pv
          persistentVolumeClaim:
            claimName: homeassistant-pvc
        - name: homeassistant-config
          configMap:
            name: homeassist-config
            defaultMode: 0777
      containers:
        - name: homeassistant
          image: "homeassistant/home-assistant:2023.4"
          volumeMounts:
            - mountPath: /config
              name: homeassistant-pv
            - mountPath: /config/configuration.yaml"
              subPath: "configuration.yaml"
              name: homeassistant-config
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP