apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reloader.stakater.com/match: "true"
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    default_config:
    http:
      use_x_forwarded_for: true
    tts:
      - platform: google_translate