apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reloader.stakater.com/match: "true"
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 172.30.33.3
        - 127.0.0.1
        - ::1

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    # Text to speech
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
