apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-pv-claim
  labels:
    app: homeassist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: homeassist-pv