apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-pvc
      containers:
        - name: homeassistant
          image: "homeassistant/home-assistant:2023.4"
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP