apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: homeassistant-pvc
      containers:
        - name: homeassistant
          image: "homeassistant/home-assistant:2023.4"
          volumeMounts:
            - name: pvc
              mountPath: /config