pihole:
  image:
    # -- the repostory to pull the image from
    repository: "pihole/pihole"
    # -- the docker tag, if left empty it will get it from the chart's appVersion
    tag: "2023.03.1"

  ingress:
    enabled: true

  persistentVolumeClaim:
    enabled: true

  serviceWeb:
    loadBalancerIP: 192.168.178.201
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  serviceDns:
    loadBalancerIP: 192.168.178.201
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  serviceDhcp:
    loadBalancerIP: 192.168.178.201
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 127.0.0.1
      - 1.1.1.1
  #! use an existing secret in a prod env
  adminPassword: "0n4BQ2l7Dbu3ViYgd4wu"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }