apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ha-dns
  namespace: homeassistant
spec:
  endpoints:
    - dnsName: "ha.joachimprinzbach.com"
      recordTTL: 180
      recordType: CNAME
      targets:
        - "joachimprinzbach.com"