apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/search: "true"
  name: homeassistant-deployment
  namespace: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: homeassistant-pv
          persistentVolumeClaim:
            claimName: homeassistant-pvc
        - name: homeassistant-config
          configMap:
            name: homeassistant-config
      containers:
        - name: homeassistant
          image: "homeassistant/home-assistant:2023.4"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: homeassistant-pv
              mountPath: /config
            - name: homeassistant-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              readOnly: true
      initContainers:
        - name: init-homeassistant
          image: busybox
          command: [ '/bin/sh', '-c' ]
          args: [ 'cp /config/configuration.yaml /config-ha/configuration.yaml; cp /config/automations.yaml /config-ha/automations.yaml; cp /config/scripts.yaml /config-ha/scripts.yaml; cp /config/scenes.yaml /config-ha/scenes.yaml' ]
          volumeMounts:
            - name: homeassistant-config
              mountPath: /config
            - name: homeassistant-pv
              mountPath: /config-ha
