apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassist-ingress
  namespace: homeassistant
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - homeassist.local
      secretName: star-app-tls
  rules:
    - host: homeassist.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassist
                port:
                  number: 443