apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassist-pv
  namespace: homeassistant
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/homeassist
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - app1.local
                - app2.local
                - app3.local
                - app4.local