apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akeyless
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless
            key: accessId
            namespace: default
          accessType:
            name: akeyless
            key: accessType
            namespace: default
          accessTypeParam:
            name: akeyless
            key: accessTypeParam
            namespace: default