apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        -
          name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.13.4
          args:
            - --source=crd
            - --crd-source-kind=DNSEndpoint
            - --provider=cloudflare
            - --domain-filter=prinzba.ch
            - --txt-prefix=extdns.
            - --interval=20s
            - --events
            - --log-level=info
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: cloudflare-api-key
            - name: CF_API_EMAIL
              value: "joachim.prinzbach@gmail.com"