apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  data:
    - remoteRef:
        key: /cloudflare/api-key
      secretKey: api-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    deletionPolicy: Delete