kind: Service
apiVersion: v1
metadata:
  name: external-service
spec:
  ports:
    - protocol: TCP
      port: 80

---

kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
subsets:
  - addresses:
      - ip: 192.168.1.2
    ports:
      - port: 8123


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
spec:
  rules:
    - host: ha.prinzba.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-service
                port:
                  number: 80
