apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: uptime-dns
spec:
  endpoints:
    - dnsName: "uptime.prinzba.ch"
      recordTTL: 180
      recordType: CNAME
      targets:
        - "prinzba.ch"