apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - base/cf-api-key-external-secret.yaml
  - base/cf-api-token-external-secret.yaml
  - base/external-dns-namespace.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/v0.13.4/docs/contributing/crd-source/crd-manifest.yaml
  - https://github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.13.4

patchesStrategicMerge:
  - overlays/external-dns-deployment.yaml
  - overlays/external-dns-cluster-role.yaml