apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-lets-encrypt
spec:
  acme:
    email: joachim.prinzbach@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: joachim.prinzbach@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key